### PR TITLE
Update PHP version for 8.0 / 8.1

### PR DESCRIPTION
**Pull request by chrisdicarlo**
Updates PHP version constraints for PHP 8.0 and 8.1.

### CODE REVIEW

**Comment by wjonkerhulst** [comment]
`"php": "^7.3|^8.0", `

should do it see also https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by chrisdicarlo** [comment]
> `"php": "^7.3|^8.0", `
> 
> should do it see also https://getcomposer.org/doc/articles/versions.md#caret-version-range-

Ah, my bad - updated!

**Comment by SeanBerce** [comment]
Yeah! Let's get this thing merged! I'm working on a Laravel 8 upgrade but still have an ERP that's nearly twice my age I have to connect to.

**Comment by keganlester** [comment]
> Yeah! Let's get this thing merged! I'm working on a Laravel 8 upgrade but still have an ERP that's nearly twice my age I have to connect to.

This is exactly what my team is going through! MERGE IT @cooperl22

**Comment by chrisdicarlo** [comment]
@SeanBerce @keganlester You could switch the dependency to my fork temporarily if you want to just keep working on your upgrade and keep composer happy - once it's merged and tagged you can switch back to the main project.

e.g. change you composer dependency to "cooperl/laravel-db2": "dev-php8-compatibility" and add the repository in composer.json: e.g.

"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/chrisdicarlo/laravel-db2"
    }
]

**Pull request merged**
