### PR TITLE
Add IBM Mainframe z/OS support

### PR DESCRIPTION
**Pull request by lucasmezencio**
There is a slightly difference between Linux/Windows and Mainframe (z\OS) versions.

### CODE REVIEW

**Comment by lucasmezencio** [comment]
Hi @cooperl22 any questions about this PR?

**Comment by lucasmezencio** [comment]
Please, dude. Can you accept this pull request?

**Comment by cooperl22** [comment]
Sure. Done!

**Comment by lucasmezencio** [comment]
Thanks a lot, dude! :smiley: :dancer:

**Pull request merged**
